### ISSUE TITLE
add module-info.java to jactor-facade

### ISSUE THREAD

**Issue by jactor-rises** [jactor-rises/jactor-rises#2]
I have added module-info.java to every maven module except jactor-facade. I am unable to create a module-info.java in this module.

The module name should be jactor.rises.facade

It all builds well in my ide, but when building with maven I get a compilation failure. I am unable to find out which file maven encounters the compile time error and why..

Help is appreciated...

**Comment by jactor-rises** [comment]
module-info trying to create:

```
module jactor.rises.facade {
    requires jactor.rises.commons;
    requires jactor.rises.model;

    requires slf4j.api;

    requires spring.beans;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires spring.context;
    requires spring.web;

    exports com.github.jactor.rises.facade.spring to spring.core;
}
```

**Comment by jactor-rises** [comment]
module-info trying to create:

```
module jactor.rises.facade {
    requires jactor.rises.commons;
    requires jactor.rises.model;

    requires slf4j.api;

    requires spring.beans;
    requires spring.boot;
    requires spring.boot.autoconfigure;
    requires spring.context;
    requires spring.web;

    exports com.github.jactor.rises.facade.spring to spring.core;
}
```

**Comment by jactor-rises** [comment]
The following error is reported from the compiler plugin:

```
[DEBUG] Adding /Users/jactor/ws/jactor-rises/jactor-applications/jactor-facade/target/generated-sources/annotations to compile source roots:
  /Users/jactor/ws/jactor-rises/jactor-applications/jactor-facade/src/main/java
[DEBUG] New compile source roots:
  /Users/jactor/ws/jactor-rises/jactor-applications/jactor-facade/src/main/java
  /Users/jactor/ws/jactor-rises/jactor-applications/jactor-facade/target/generated-sources/annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jactor-rises ....................................... SUCCESS [  1.177 s]
[INFO] jactor-rises::jactor-commons ....................... SUCCESS [  8.606 s]
[INFO] jactor-rises::jactor-test .......................... SUCCESS [  1.412 s]
[INFO] jactor-rises::jactor-model ......................... SUCCESS [  2.097 s]
[INFO] jactor-rises::jactor-applications::jactor-persistence-orm SUCCESS [ 18.781 s]
[INFO] jactor-rises::jactor-applications::jactor-facade ... FAILURE [  0.143 s]
[INFO] jactor-rises::jactor-applications::jactor-web ...... SKIPPED
[INFO] jactor-rises::jactor-applications .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.141 s
[INFO] Finished at: 2018-08-15T20:56:36+02:00
[INFO] Final Memory: 46M/188M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project jactor-facade: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile failed.: IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project jactor-facade: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.codehaus.plexus.languages.java.jpms.AsmModuleInfoParser.parse(AsmModuleInfoParser.java:80)
	at org.codehaus.plexus.languages.java.jpms.AsmModuleInfoParser.getModuleDescriptor(AsmModuleInfoParser.java:65)
	at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePaths(LocationManager.java:113)
	at org.apache.maven.plugin.compiler.CompilerMojo.preparePaths(CompilerMojo.java:219)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:762)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jactor-facade
```

running with `mvn clean install -e -X`

**Comment by jactor-rises** [comment]
the following is reported when running `mvn help:effective-pom | grep -B 2 -A 2 compiler`

```
    <maven-assembly-plugin.version>3.1.0</maven-assembly-plugin.version>
    <maven-clean-plugin.version>3.0.0</maven-clean-plugin.version>
    <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
    <maven-dependency-plugin.version>3.0.2</maven-dependency-plugin.version>
    <maven-deploy-plugin.version>2.8.2</maven-deploy-plugin.version>
--
--
    <maven-surefire-plugin.version>2.21.0</maven-surefire-plugin.version>
    <maven-war-plugin.version>3.1.0</maven-war-plugin.version>
    <maven.compiler.source>10</maven.compiler.source>
    <maven.compiler.target>10</maven.compiler.target>
    <micrometer.version>1.0.5</micrometer.version>
    <mockito.version>2.15.0</mockito.version>
--
--
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
          <configuration>
--
--
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <executions>
```

**Comment by jactor-rises** [comment]
An issue is created on the maven plugin project: https://issues.apache.org/jira/browse/MCOMPILER-358

**Comment by rfscholte** [comment]
try maven-compiler-plugin 3.8.0 first...

**Comment by jactor-rises** [comment]
no sigar... :(

same exception
no meaningful explanation
the following is tried, `git diff`:

```
diff --git a/jactor-applications/jactor-facade/pom.xml b/jactor-applications/jactor-facade/pom.xml
index 14f0c6d7..1e78e0b1 100644
--- a/jactor-applications/jactor-facade/pom.xml
+++ b/jactor-applications/jactor-facade/pom.xml
@@ -22,6 +22,7 @@
         <java.version>10</java.version>
         <junit-jupiter.version>5.0.3</junit-jupiter.version>
         <junit-platform.version>1.0.3</junit-platform.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
         <mvn-surefire.version>2.19.1</mvn-surefire.version>
     </properties>
 
diff --git a/jactor-applications/jactor-persistence-orm/pom.xml b/jactor-applications/jactor-persistence-orm/pom.xml
index 4d4cca66..72d23471 100644
--- a/jactor-applications/jactor-persistence-orm/pom.xml
+++ b/jactor-applications/jactor-persistence-orm/pom.xml
@@ -23,6 +23,7 @@
         <javax-xml-bind.version>2.3.0</javax-xml-bind.version>
         <junit-jupiter.version>5.0.3</junit-jupiter.version>
         <junit-platform.version>1.0.3</junit-platform.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
         <mvn-surefire.version>2.19.1</mvn-surefire.version>
     </properties>
 
diff --git a/jactor-applications/jactor-web/pom.xml b/jactor-applications/jactor-web/pom.xml
index 3bcb8a0a..fdd74122 100755
--- a/jactor-applications/jactor-web/pom.xml
+++ b/jactor-applications/jactor-web/pom.xml
@@ -26,7 +26,7 @@
         <junit-jupiter.version>5.0.3</junit-jupiter.version>
         <junit-platform.version>1.0.3</junit-platform.version>
 
-        <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
         <mvn-surefire.version>2.19.1</mvn-surefire.version>
         <webjars-bootstrap.version>4.0.0</webjars-bootstrap.version>
         <webjars-jquery.version>3.3.1</webjars-jquery.version>
diff --git a/pom.xml b/pom.xml
index 83233ff6..3f35dd22 100644
--- a/pom.xml
+++ b/pom.xml
@@ -26,7 +26,7 @@
         <junit-platform.version>1.0.3</junit-platform.version>
         <junit-vintage.version>${junit.version}.3</junit-vintage.version>
 
-        <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
         <maven-jdeps.version>3.1.1</maven-jdeps.version>
         <maven-site-plugin.version>3.6</maven-site-plugin.version>
         <maven-source-plugin.version>3.0.1</maven-source-plugin.version>
```

**Comment by rfscholte** [comment]
jactor-facade uses spring-boot-starter-parent as parent, so you must redefine your plugins here. Please see the logging. Make sure you use maven-compiler-plugin 3.8.0 and maven-surefire-plugin 2.22.0. If the build fails, first check if you're using the right/most recent versions of the plugins.

**Comment by rfscholte** [comment]
Just add the following to jactor-facade:

	<build>
	  <pluginManagement>
	    <plugins>
		  <plugin>
		    <groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.8.0</version>
		  </plugin>
		  <plugin>
		    <groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.22.0</version>
		  </plugin>
		</plugins>
	  </pluginManagement>
	</build>

Now you will have failing tests due to unopened modules...

**Comment by jactor-rises** [comment]
sorry, no sigar... same error. all modules until `jactor.rises.facade`builds ok... `git diff`:

```
+diff --git a/jactor-applications/jactor-facade/pom.xml b/jactor-applications/jactor-facade/pom.xml
index 14f0c6d7..bab01591 100644
--- a/jactor-applications/jactor-facade/pom.xml
+++ b/jactor-applications/jactor-facade/pom.xml
@@ -22,7 +22,8 @@
         <java.version>10</java.version>
         <junit-jupiter.version>5.0.3</junit-jupiter.version>
         <junit-platform.version>1.0.3</junit-platform.version>
-        <mvn-surefire.version>2.19.1</mvn-surefire.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
+        <mvn-surefire.version>2.22.0</mvn-surefire.version>
     </properties>
 
     <dependencies>
@@ -106,4 +107,20 @@
             </exclusions>
         </dependency>
     </dependencies>
+    <build>
+        <pluginManagement>
+            <plugins>
+                <plugin>
+                    <groupId>org.apache.maven.plugins</groupId>
+                    <artifactId>maven-compiler-plugin</artifactId>
+                    <version>${maven-compiler-plugin.version}</version>
+                </plugin>
+                <plugin>
+                    <groupId>org.apache.maven.plugins</groupId>
+                    <artifactId>maven-surefire-plugin</artifactId>
+                    <version>${maven-surefire-plugin.version}</version>
+                </plugin>
+            </plugins>
+        </pluginManagement>
+    </build>
 </project>
diff --git a/jactor-applications/jactor-persistence-orm/pom.xml b/jactor-applications/jactor-persistence-orm/pom.xml
index 4d4cca66..72d23471 100644
--- a/jactor-applications/jactor-persistence-orm/pom.xml
+++ b/jactor-applications/jactor-persistence-orm/pom.xml
@@ -23,6 +23,7 @@
         <javax-xml-bind.version>2.3.0</javax-xml-bind.version>
         <junit-jupiter.version>5.0.3</junit-jupiter.version>
         <junit-platform.version>1.0.3</junit-platform.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
         <mvn-surefire.version>2.19.1</mvn-surefire.version>
     </properties>
 
diff --git a/jactor-applications/jactor-web/pom.xml b/jactor-applications/jactor-web/pom.xml
index 3bcb8a0a..fdd74122 100755
--- a/jactor-applications/jactor-web/pom.xml
+++ b/jactor-applications/jactor-web/pom.xml
@@ -26,7 +26,7 @@
         <junit-jupiter.version>5.0.3</junit-jupiter.version>
         <junit-platform.version>1.0.3</junit-platform.version>
 
-        <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
         <mvn-surefire.version>2.19.1</mvn-surefire.version>
         <webjars-bootstrap.version>4.0.0</webjars-bootstrap.version>
         <webjars-jquery.version>3.3.1</webjars-jquery.version>
diff --git a/pom.xml b/pom.xml
index 83233ff6..3f35dd22 100644
--- a/pom.xml
+++ b/pom.xml
@@ -26,7 +26,7 @@
         <junit-platform.version>1.0.3</junit-platform.version>
         <junit-vintage.version>${junit.version}.3</junit-vintage.version>
 
-        <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
+        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
         <maven-jdeps.version>3.1.1</maven-jdeps.version>
         <maven-site-plugin.version>3.6</maven-site-plugin.version>
         <maven-source-plugin.version>3.0.1</maven-source-plugin.version>
```
